# Makefile with Automatic Compiler Detection (nvcc/g++)
#
# This Makefile checks for the presence of the NVIDIA CUDA Compiler (nvcc).
# - If nvcc is found, it compiles the project with CUDA support.
# - If nvcc is not found, it falls back to using g++.

# --- Configuration ---

# Target executable name and location.
TARGET_DIR = $(HOME)
TARGET_NAME = cnet
TARGET = $(TARGET_DIR)/$(TARGET_NAME)

# Directory for build artifacts (object files).
BUILD_DIR = build
OBJ_DIR = $(BUILD_DIR)/obj

# --- Compiler Auto-Detection ---

# Check if the 'nvcc' command exists in the system's PATH.
NVCC_RESULT := $(shell which nvcc 2>/dev/null)
NVCC_TEST := $(notdir $(NVCC_RESULT))

# --- Conditional Build Configuration ---

ifeq ($(NVCC_TEST),nvcc)
    # --- NVCC Configuration (CUDA Build) ---
    INFO_MSG = "==> NVCC detected. Building with CUDA support."
    CXX = nvcc
    # Flags for nvcc:
    # -x cu: Treat all source files as CUDA files.
    # -Xcompiler -fopenmp: Pass the -fopenmp flag to the host compiler (like g++).
    # -MMD -MP: emit a .d file per object listing the headers it includes, so
    # header edits trigger the right recompiles (-MP adds phony header targets
    # so a removed header doesn't break the build).
    CXXFLAGS = -x cu -std=c++11 -Xcompiler -fopenmp -O2 -MMD -MP --default-stream per-thread
    LDFLAGS = -lgomp -lcufft -lcublas # OpenMP + cuFFT + cuBLAS (TokenwiseLinear GEMMs).
    # NCCL is only needed by code that does multi-GPU all-reduce. The dp_shakespeare
    # example links it directly; MAINLIBS adds it to the dev main (gpu_tests.h uses
    # it) and is patched empty for the public main by github_export.sh.
    MAINLIBS =
    SRCS = utils/flags.cpp \
           gpu/gpu_func.cpp \
           impl/vars.cpp \
           gpu/kernels.cpp \
           gpu/reduce.cpp \
           gpu/reducegrad.cpp \
           cnet.cpp

else
    # --- G++ Configuration (Standard Build) ---
    INFO_MSG = "==> NVCC not found. Building with g++."
    CXX = g++
    # Note: -Xclang is specific to the Clang frontend. -fopenmp is the standard g++ flag.
    CXXFLAGS = -std=c++11 -Xclang -fopenmp -O2 -MMD -MP
    LDFLAGS = -lomp # Link with the OpenMP library.
    SRCS = utils/flags.cpp \
           impl/vars.cpp \
           gpu/gpu_func.cpp \
           gpu/reduce.cpp \
           gpu/reducegrad.cpp \
           gpu/kernels.cpp \
           cnet.cpp
endif

# --- Automatic Variable Generation ---

# VPATH tells 'make' where to look for source files.
# This is created automatically from the unique directory paths in the SRCS variable.
VPATH = $(sort $(dir $(SRCS))) examples

# Generate object file names, placing them in the OBJ_DIR.
# This handles both .cpp and .cu files correctly.
# e.g., gpu/reduce.cpp becomes build/obj/reduce.o
# e.g., gpu/gpu_func.cu becomes build/obj/gpu_func.o
OBJS = $(addprefix $(OBJ_DIR)/, $(notdir $(SRCS:.cpp=.o)))
OBJS := $(subst .cu,.o,$(OBJS))

# Per-object dependency files (generated by -MMD); pulled in at the bottom so
# each .o is rebuilt when any header it includes changes.
DEPS = $(OBJS:.o=.d)


# Framework objects (everything except the selected main), reused by example mains.
FW_SRCS = utils/flags.cpp gpu/gpu_func.cpp impl/vars.cpp gpu/kernels.cpp gpu/reduce.cpp gpu/reducegrad.cpp
FW_OBJS = $(addprefix $(OBJ_DIR)/, $(notdir $(FW_SRCS:.cpp=.o)))


# --- Build Rules ---

# Phony targets are not actual files. 'all' is the default goal.
.PHONY: all clean run info dp_shakespeare generate
.DEFAULT_GOAL := all

# Standalone multi-GPU data-parallel tiny-shakespeare example (its own main).
dp_shakespeare: $(FW_OBJS) $(OBJ_DIR)/dp_shakespeare.o
	@mkdir -p $(TARGET_DIR)
	$(CXX) $^ $(LDFLAGS) -lnccl -o $(TARGET_DIR)/dp_shakespeare
	@echo "==> Built $(TARGET_DIR)/dp_shakespeare"

# Standalone CPU-only text generator (its own main; no CUDA/NCCL).
generate: $(FW_OBJS) $(OBJ_DIR)/generate.o
	@mkdir -p $(TARGET_DIR)
	$(CXX) $^ $(LDFLAGS) -o $(TARGET_DIR)/generate
	@echo "==> Built $(TARGET_DIR)/generate"

# Default target: build the final executable.
all: $(TARGET)

# Rule to link the final executable from all the object files.
$(TARGET): $(OBJS)
	@echo "==> Linking target: $@"
	@mkdir -p $(TARGET_DIR) # Ensure the target directory exists.
	$(CXX) $^ $(LDFLAGS) $(MAINLIBS) -o $@
	@echo "==> Build complete. Executable is at $(TARGET)"

# Generic pattern rule to compile any source file (.cpp or .cu) into an object file.
# This works because both nvcc (with -x cu) and g++ can handle .cpp files.
# The VPATH variable allows 'make' to find the source file in its original directory.
$(OBJ_DIR)/%.o: %.cpp
	@echo "==> Compiling $<..."
	@mkdir -p $(OBJ_DIR) # Ensure the object directory exists.
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: %.cu
	@echo "==> Compiling $<..."
	@mkdir -p $(OBJ_DIR) # Ensure the object directory exists.
	$(CXX) $(CXXFLAGS) -c $< -o $@


# --- Utility Rules ---

# Rule to display which compiler is being used.
info:
	@echo $(INFO_MSG)

# Rule to run the compiled application.
run: all
	@echo "==> Running application..."
	@$(TARGET)
	@echo "==> Application finished."

# Rule to clean up all generated files.
clean:
	@echo "==> Cleaning up build artifacts..."
	@rm -rf $(BUILD_DIR) $(TARGET)
	@echo "==> Cleanup complete."

# Pull in the generated header dependencies (silently absent on a fresh build).
-include $(DEPS)


